[package]
name = "robot_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
env_logger = "0.11.8"
log.workspace = true
robot_web = { path = "../robot_web" }
pca9685-rppal = "0.1.0"
rppal = "0.22.1"