[package]
name = "robot_main"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
robot_core = { path = "../robot_core" }